import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';

const inter = Inter({subsets: ['latin']});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`flex bg-[#DDE3F1] mx-auto max-w-[556px] px-5 min-h-screen ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}

export {metadata};
